-- V3.2 trip reviews: one shipper rating (1-5 stars) and an optional comment per COMPLETED trip.
-- Additive only. Reviews never change trip status, fleet reputation or any settlement.

CREATE TABLE trip_reviews (
    id UUID PRIMARY KEY,                          -- UUIDv7 generated by the service
    trip_id UUID NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    shipper_id UUID NOT NULL,                     -- copied from the trip; never taken from the client
    carrier_id UUID NOT NULL,                     -- copied from the trip; never taken from the client
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment VARCHAR(1000),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_trip_reviews_trip UNIQUE (trip_id)  -- at most one review per trip, also under races
);

CREATE INDEX idx_trip_reviews_carrier_created ON trip_reviews (carrier_id, created_at DESC);
