package iuh.fit.se.contractservice.domain.entity;

import iuh.fit.se.contractservice.domain.enums.TripStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.Instant;
import java.util.UUID;

@Entity
@Table(name = "trip_location_updates")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TripLocationUpdate {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "trip_id", nullable = false)
    private Trip trip;

    @Enumerated(EnumType.STRING)
    @Column(name = "actor_role", length = 20)
    private iuh.fit.se.contractservice.domain.enums.AccountRole actorRole;

    @Column(name = "milestone_id")
    private UUID milestoneId;

    @Column(name = "actor_id", nullable = false)
    private UUID actorId;

    /** ACCOUNT, or DRIVER_SESSION when actorId is a code-login driver session (not an account). */
    @Column(name = "actor_type", nullable = false, length = 20)
    @Builder.Default
    private String actorType = "ACCOUNT";

    @Column(nullable = false)
    private Double latitude;

    @Column(nullable = false)
    private Double longitude;

    @Column(length = 160)
    private String label;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private TripLocationSource source;

    @Enumerated(EnumType.STRING)
    @Column(length = 30)
    private TripStatus status;

    @Column(name = "tracking_session_id")
    private UUID trackingSessionId;

    @Column(name = "sample_id")
    private UUID sampleId;

    @Column(name = "captured_at")
    private Instant capturedAt;

    @Column(name = "accuracy_meters")
    private Double accuracyMeters;

    @org.hibernate.annotations.Generated(event = org.hibernate.generator.EventType.INSERT)
    @Column(name = "ingestion_sequence", nullable = false, insertable = false, updatable = false,
            columnDefinition = "bigint generated by default as identity")
    private Long ingestionSequence;

    @CreationTimestamp
    @Column(name = "recorded_at", nullable = false, updatable = false)
    private Instant recordedAt;
}
